name: サポート依頼
description: サポート依頼だよ
title: 分かりやすいタイトル
labels: []
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        サポート依頼ありがとう。長いけどがんばって書いてね
  - type: textarea
    attributes:
      label: 概略
      description: 簡単な説明を書いてね
    validations:
      required: true
  - type: dropdown
    attributes:
      label: タイプ
      options:
        - A
        - B
        - C
      multiple: true
    validations:
      required: true
  - type: input
    attributes:
      label: ID
      description: hoge ID をいれてね
  - type: textarea
    attributes:
      label: 解決したいこと
      description: 期待値合わせをしたいので明示してね
    validations:
      required: true
  - type: textarea
    attributes:
      label: 詳細
      description: その他ログなどをできるだけ詳細に書いてね
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: 起票前の確認
      description: |
        以下を確認してね
      options:
        - label: aaa
          required: true
        - label: bbb
          required: true
        - label: ccc
          required: true
  - type: input
    attributes:
      label: 通知テスト
      description: 一次担当者への通知用だよ。変更しないでね
      value: |
        @upinetree
