name: Checkout merge commit from pull request
on:
  workflow_dispatch:
    inputs:
      pull-request-number:
        description: "Pull request number"
        required: true
        type: number

jobs:
  checkout-merge-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the target commit sha
        id: git-sha
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr_number = ${{ github.event.inputs.pull-request-number }};
            console.log('pull-request-number', pr_number);

            console.log('pull-request-number from core.getInput', core.getInput('pull-request-number')); // 取れない…

            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.inputs.pull-request-number }}
            });
            console.log('merge_commit_sha', pr.merge_commit_sha);
            core.exportVariable('MERGE_COMMIT_SHA', pr.merge_commit_sha);
      - name: Checkout the merge commit
        uses: actions/checkout@v4
        with:
          ref: ${{ env.MERGE_COMMIT_SHA }}
      - name: Show the commit log
        run: git show

  post-job:
    needs: checkout-merge-commit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: [1, 2]
    steps:
      - name: Post job
        run: |
          echo "Post job ${{ matrix.value }}"
          echo "pull-request-number: ${{ github.event.inputs.pull-request-number }}"
          echo "pull-request-number from inputs: ${{ inputs.pull-request-number }}"
