name: Lint for a pull request body
on:
  pull_request:
    types:
      - opened
      - edited # レビュー用のサンプルブランチ用

jobs:
  ensure-pr-description-content:
    runs-on: ubuntu-latest
    name: 'Ensure pr description has an expected word if a specific file exists'
    steps:
      - uses: actions/checkout@v2
      - name: 'Fetch branches'
        run: |
          git fetch --depth 1 origin ${{ github.base_ref }}
      - name: 'Check if a pull request description is expeced as its file diffs'
        env:
          PULL_REQUEST_BODY: "${{ github.event.pull_request.body }}"
          TARGET_FILES_PATTERN: oneshot/
          VALID_PATTERN: テンプレだよ
        run: bash actions/lint_pr_body.sh
      - name: 'Comment this result to a pull request'
        if: ${{ env.invalid_body == 'true' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            pull request の説明にテンプレートを利用してください
      - uses: upinetree/labeler@fix-pull-request-param
        with:
          add-labels: "oneshot"
