name: Lint for a pull request body
on:
  pull_request:
    types:
      - opened
      - edited # レビュー用のサンプルブランチ用

jobs:
  ensure-pr-description-content:
    runs-on: ubuntu-latest
    name: 'Ensure pr description has an expected word if a specific file exists'
    steps:
      - uses: actions/checkout@v2
      - name: 'Check if target files are included in a PR'
        run: |
          git diff ${{ github.base_ref }} ${{ github.head_ref }} --name-only --diff-filter=AM | grep oneshot/
          test $? -eq 0 && echo "target_file_exists=true" >> $GITHUB_ENV || echo "no target files!"
      - name: 'Check if PR description contains a specific keyword in the template'
        if: ${{ env.target_file_exists == 'true' }}
        run: |
          echo "${{ github.event.pull_request.body }}" | tr -d '\r\n' | grep -v 'テンプレだよ' && echo "invalid_body=true" >> $GITHUB_ENV
      - name: 'Comment this result to a pull request' # このあとラベルなかったらつけるのも試したい https://github.com/actions/starter-workflows/blob/8ba0ca0797f1852b9f689a07c015c19bc723c980/automation/label.yml
        if: ${{ env.invalid_body == 'true' }}
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            pull request の説明にテンプレートを利用してください
